config/routes.rb
Rails.application.routes.draw do
  get 'tutor/index'
  get 'students/index'
  resources :courses
  devise_for :tutors
  devise_for :students
  root "home#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :tutor

  validates :title, :technologies, :table_of_contents, presence: true
  validates :duration, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :free_or_paid, presence: true, inclusion: { in: %w(free paid) }

  validates :price, presence: true, numericality: { greater_than: 0 }, if: :paid_course?

  def paid_course?
    free_or_paid == 'paid'
  end
  
  def duration_months
    duration / 30
  end

  def duration_days
    duration % 30
  end

  def duration=(value)
    self[:duration] = value.to_i
  end

  def formatted_duration
    "#{duration_months} months #{duration_days} days"
  end
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10}\z/, message: "must be a valid 10-digit phone number" }
  validates :education_qualification, presence: true
end

app/models/tutor.rb
class Tutor < ApplicationRecord
  has_many :courses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    if resource_class == Student
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :education_qualification])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :education_qualification])
    elsif resource_class == Tutor
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone,:education_qualification, :profession, :work_experience ])
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone,:education_qualification, :profession, :work_experience])
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_tutor!

  def index
    @courses = current_tutor.courses
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = current_tutor.courses.build(course_params)

    if @course.save
      redirect_to courses_path, notice: 'Course created successfully.'
    else
      render :new
    end
  end

  private

  def course_params
    params.require(:course).permit(:title, :technologies, :duration, :table_of_contents, :free_or_paid, :price)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_student!
  
  def index
  end
end

app/controllers/tutor_controller.rb
class TutorController < ApplicationController
  before_action :authenticate_tutor!
  def index
    @courses = current_tutor.courses
    @course = Course.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tutor_helper.rb
module TutorHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>
      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :technologies %>
    <%= form.text_field :technologies %>
  </div>
  <div class="field">
  <%= form.label :duration, "Duration (Months and Days)" %>
  <%= form.number_field :duration, placeholder: "Total Duration in Days" %>
</div>
  
  <div class="field">
    <%= form.label :table_of_contents %>
    <%= form.text_area :table_of_contents %>
  </div>
  
  <div class="field">
    <%= form.label :free_or_paid %>
    <%= form.select :free_or_paid, options_for_select([['Free', 'free'], ['Paid', 'paid']], course.free_or_paid), prompt: "Select" %>
  </div>
  
  <div class="field" id="price-field" style="<%= 'display: none;' if course.free_or_paid != 'paid' %>">
    <%= form.label :price %>
    <%= form.number_field :price, step: "1", inputmode: "numeric", pattern: "[0-9]*", placeholder: "₹" %>
  </div>

  <div>
    <%= form.submit "Submit" %>
  </div>
<% end %>



app/views/courses/index.html.erb
<h1>All Courses</h1>
<ul>
  <% @courses.each do |course| %>
    <li><%= link_to course.title, course_path(course) %></li>
  <% end %>
</ul>

app/views/courses/new.html.erb
<h1>New Course</h1>
<%= render 'courses/form', course: @course %>


app/views/courses/show.html.erb
<h2><%= @course.title %></h2>

<div>
  <strong>Technologies:</strong>
  <%= @course.technologies %>
</div>

<div>
  <strong>Duration:</strong>
   <%= @course.formatted_duration %>
</div>

<div>
  <strong>Table of Contents:</strong>
  <%= @course.table_of_contents %>
</div>

<div>
  <strong>Free or Paid:</strong>
  <%= @course.free_or_paid.nil? ? "Not specified" : @course.free_or_paid.capitalize %>
</div>

<% if @course.free_or_paid == 'paid' %>
  <div>
    <strong>Price:</strong>
    <%= number_to_currency(@course.price, unit: "₹") %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to the Easy Learn Portal</h1>

<%= link_to "Tutor Login", tutor_index_path, class: "btn btn-primary" %>
<%= link_to "Student Login", students_index_path, class: "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyLearn</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |key, message| %>
      <div class="flash <%= key %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<h1>Welcome to the Student Portal</h1>

<% if student_signed_in? %>
  <p>Welcome, <%= "#{current_student.first_name} #{current_student.last_name}" %>!</p>
  <%= link_to 'Edit profile', edit_student_registration_path %>
  <%= link_to "Sign out", destroy_student_session_path, data: { turbo_method: :delete } %>
<% else %>
  <%= link_to 'Log in', new_student_session_path %>
  <%= link_to 'Sign up', new_student_registration_path %>
<% end %>

app/views/tutor/index.html.erb
<h1>Welcome to the Tutor Portal</h1>

<% if tutor_signed_in? %>
  <%= link_to 'Edit profile', edit_tutor_registration_path %>
  <%= link_to "Sign out", destroy_tutor_session_path, data: { turbo_method: :delete } %><br>
  <%= link_to 'Create a new course', new_course_path %>
  <h1>Your Courses</h1>

  

<% @courses.each do |course| %>
  <div>
    <h2><%= course.title %></h2>

    <div>
      <strong>Technologies:</strong>
      <%= course.technologies %>
    </div>

    <div>
    <strong>Duration:</strong>
     <%= @course.formatted_duration %>
    </div>

    <div>
      <strong>Table of Contents:</strong>
      <%= course.table_of_contents %>
    </div>

    <div>
    <strong>Free or Paid:</strong>
    <%= course.free_or_paid.present? ? course.free_or_paid.capitalize : "Not specified" %>
  </div>

  <% if course.free_or_paid == "paid" %>
  <div>
    <strong>Price:</strong>
    <%= number_to_currency(course.price, unit: "₹") %>
  </div>
<% end %>

  </div>
<% end %>

  
  
<% else %>
  <%= link_to 'Log in', new_tutor_session_path %>
  <%= link_to 'Sign up', new_tutor_registration_path %>
<% end %>